<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <Title>Lombiq Training Demo for Orchard Core</Title>
    <Description>Orchard Core training demo module for teaching Orchard Core fundamentals primarily by going through its source code.</Description>
    <PackageLicenseUrl>https://github.com/Lombiq/Orchard-Training-Demo-Module/blob/dev/License.md</PackageLicenseUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Orchard-Training-Demo-Module</PackageProjectUrl>
    <PackageTags>Orchard Core, Orchard CMS, training</PackageTags>
    <DefaultItemExcludes>$(DefaultItemExcludes);.git*</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\Readme.md" Link="Readme.md" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.LibraryManager.Build" Version="3.0.71" />
    <PackageReference Include="OrchardCore.Users.Abstractions" Version="3.0.0-preview-18892" />
    <PackageReference Include="OrchardCore.Workflows.Abstractions" Version="3.0.0-preview-18892" />
    <PackageReference Include="OrchardCore.BackgroundTasks" Version="3.0.0-preview-18892" />
    <PackageReference Include="OrchardCore.ContentFields" Version="3.0.0-preview-18892" />
    <PackageReference Include="OrchardCore.ContentManagement" Version="3.0.0-preview-18892" />
    <PackageReference Include="OrchardCore.ContentTypes.Abstractions" Version="3.0.0-preview-18892" />
    <PackageReference Include="OrchardCore.Data.Abstractions" Version="3.0.0-preview-18892" />
    <PackageReference Include="OrchardCore.DynamicCache" Version="3.0.0-preview-18892" />
    <PackageReference Include="OrchardCore.FileStorage.FileSystem" Version="3.0.0-preview-18892" />
    <PackageReference Include="OrchardCore.Indexing.Abstractions" Version="3.0.0-preview-18892" />
    <PackageReference Include="OrchardCore.Media.Abstractions" Version="3.0.0-preview-18892" />
    <PackageReference Include="OrchardCore.Module.Targets" Version="3.0.0-preview-18892" />
    <!-- Note that you need to add a reference to OrchardCore.ResourceManagement for the basic tag helpers like <style>
    and <script> to properly work when the app is built for production (and thus Razor Runtime Compilation is turned
    off. OrchardCore.DisplayManagement is needed for a variety of things but also for the <shape> tag helper for the
    same reason. -->
    <PackageReference Include="OrchardCore.ResourceManagement" Version="3.0.0-preview-18892" />
    <PackageReference Include="OrchardCore.DisplayManagement" Version="3.0.0-preview-18892" />
  </ItemGroup>

  <!-- This module requires Lombiq.HelpfulLibraries.OrchardCore, and it can be included two ways. The PackageReference
  is used by the standalone solution, while ProjectReference is needed when including the module in
  https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions. Only one of the two is ever active. -->

  <ItemGroup Condition="Exists('..\..\..\Libraries\Lombiq.HelpfulLibraries\Lombiq.HelpfulLibraries.OrchardCore\Lombiq.HelpfulLibraries.OrchardCore.csproj')">
    <ProjectReference Include="..\..\..\Libraries\Lombiq.HelpfulLibraries\Lombiq.HelpfulLibraries.OrchardCore\Lombiq.HelpfulLibraries.OrchardCore.csproj" />
  </ItemGroup>

  <ItemGroup Condition="!Exists('..\..\..\Libraries\Lombiq.HelpfulLibraries\Lombiq.HelpfulLibraries.OrchardCore\Lombiq.HelpfulLibraries.OrchardCore.csproj')">
    <PackageReference Include="Lombiq.HelpfulLibraries.OrchardCore" Version="12.5.1-alpha.6.osoe-925" />
  </ItemGroup>

</Project>
