name: Verify Pull Request

on:
  pull_request:

env:
  PULL_REQUEST_TITLE: ${{ github.event.pull_request.title }}

defaults:
  run:
    shell: pwsh

jobs:
  call-verify-workflow:
    uses: Lombiq/GitHub-Actions/.github/workflows/verify.yml@issue/OSOE-131